
import { useNavigate } from "react-router-dom";
import { Button } from "flowbite-react";
import { FaHome } from "react-icons/fa";
import BlogComponent from "../components/BlogComponent";


const PrivacyPolicyPage = () => {
      const navigate = useNavigate();

      const returnToHome = () => {
        navigate("/");
      };
  return (
    <>
      <div className="max-w-4xl mx-auto p-8">
        <BlogComponent
          title="Privacy Policy"
          tagline="Last updated: February 29, 2024"
          sections={[
            {
              subtitle: "Introduction",
              paragraphs: [
                "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
                "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
              ],
            },
            {
              subtitle: "Interpretation and Definitions",
              paragraphs: [
                "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
                "For the purposes of this Privacy Policy:",
                "- Account means a unique account created for You to access our Service or parts of our Service.",
                "- Affiliate means an entity that controls, is controlled by or is under common control with a party, where control means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
                "- Company (referred to as either the Company, We, Us or Our in this Agreement) refers to ACT Immigration And Labour Consultants, 255 Caledon Street Central Kariega, Eastern Cape South Africa.",
                "- Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
                "- Country refers to: South Africa",
                "- Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
                "- Personal Data is any information that relates to an identified or identifiable individual.",
                "- Service refers to the Website.",
                "- Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
                "- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
                "- Website refers to ACTImmigration, accessible from https://www.actimmigration.co.za/",
                "- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
              ],
            },
            {
              subtitle: "Types of Data Collected",
              paragraphs: [
                "Personal Data",
                "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
                "Email address",
                "First name and last name",
                "Phone number",
                "Address, State, Province, ZIP/Postal code, City",
                "Usage Data",
                "Usage Data is collected automatically when using the Service.",
                "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
                "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
                "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
              ],
            },
            {
              subtitle: "Use of Your Personal Data",
              paragraphs: [
                "The Company may use Personal Data for the following purposes:",
                "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, services , including the security updates, when necessary or reasonable for their implementation.",
                "To manage Your requests: To attend and manage Your requests to Us.",
                "- With other legal professionals or entities involved in Your legal matters, such as co-counsel, expert witnesses, and other entities involved in Your legal matters.",
                "- With Your consent or as required by law.",
              ],
            },
          ]}
        />
        <Button
          label="Back to Home"
          type="button"
          onClick={returnToHome}
          className="fixed bottom-16 right-4 p-3 text-white font-medium text-xs leading-tight rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg bg-gray-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
          style={{ backgroundColor: "#0e5a97", width: "40px", height: "40px" }}
        >
          <FaHome className="w-4 h-4" />
        </Button>
      </div>
    </>
  );
};

export default PrivacyPolicyPage;
